export enum ApplicationStage {
  RM = 'RM',
  BM = 'BM',
  CM = 'CM',

  CREDIT = 'CREDIT',
  CREDIT_MAKER = 'CREDIT_MAKER',
  CREDIT_CHECKER = 'CREDIT_CHECKER',

  VALUATION = 'VALUATION',
  LEGAL = 'LEGAL',

  OPS_MAKER = 'OPS_MAKER',
  OPS_HEAD = 'OPS_HEAD',
  OPS_CHECKER = 'OPS_CHECKER',

  SANCTION = 'SANCTION',
  AGREEMENT = 'AGREEMENT',
  DISBURSEMENT = 'DISBURSEMENT',

  LMS = 'LMS',
  ACTIVE = 'ACTIVE',
  COLLECTION = 'COLLECTION',
  CLOSED = 'CLOSED',
}
