export enum ApplicationStatus {
  // RM flow
  DRAFT = 'DRAFT',
  LEAD_CREATED = 'LEAD_CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED_TO_BM = 'SUBMITTED_TO_BM',

  // BM flow
  BM_PENDING = 'BM_PENDING',
  BM_QUERY = 'BM_QUERY',
  BM_APPROVED = 'BM_APPROVED',
  BM_REJECTED = 'BM_REJECTED',

  // CM flow
  CM_PENDING = 'CM_PENDING',
  CM_QUERY = 'CM_QUERY',
  CM_APPROVED = 'CM_APPROVED',
  CM_REJECTED = 'CM_REJECTED',

  // Credit maker/checker flow
  CREDIT_MAKER_PENDING = 'CREDIT_MAKER_PENDING',
  CREDIT_MAKER_QUERY = 'CREDIT_MAKER_QUERY',
  CREDIT_MAKER_RECOMMENDED = 'CREDIT_MAKER_RECOMMENDED',
  CREDIT_MAKER_REJECTED = 'CREDIT_MAKER_REJECTED',

  CREDIT_CHECKER_PENDING = 'CREDIT_CHECKER_PENDING',
  CREDIT_CHECKER_QUERY = 'CREDIT_CHECKER_QUERY',
  CREDIT_CHECKER_APPROVED = 'CREDIT_CHECKER_APPROVED',
  CREDIT_CHECKER_REJECTED = 'CREDIT_CHECKER_REJECTED',

  // Generic credit status if needed
  CREDIT_PENDING = 'CREDIT_PENDING',
  CREDIT_APPROVED = 'CREDIT_APPROVED',
  CREDIT_REJECTED = 'CREDIT_REJECTED',

 

  // Valuation
  VALUATION_PENDING = 'VALUATION_PENDING',
  VALUATION_QUERY = 'VALUATION_QUERY',
  VALUATION_APPROVED = 'VALUATION_APPROVED',
  VALUATION_REJECTED = 'VALUATION_REJECTED',
  
 // Legal
  LEGAL_PENDING = 'LEGAL_PENDING',
  LEGAL_QUERY = 'LEGAL_QUERY',
  LEGAL_APPROVED = 'LEGAL_APPROVED',
  LEGAL_REJECTED = 'LEGAL_REJECTED',
  // Sanction
  SANCTION_PENDING = 'SANCTION_PENDING',
  SANCTION_APPROVED = 'SANCTION_APPROVED',
  SANCTION_REJECTED = 'SANCTION_REJECTED',

  // Agreement / documentation
  AGREEMENT_PENDING = 'AGREEMENT_PENDING',
  AGREEMENT_COMPLETED = 'AGREEMENT_COMPLETED',

  DOCUMENTATION_PENDING = 'DOCUMENTATION_PENDING',
  DOCUMENTATION_COMPLETED = 'DOCUMENTATION_COMPLETED',

  // Disbursement
  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED',

  // Loan lifecycle
  ACTIVE = 'ACTIVE',
  COLLECTION_PENDING = 'COLLECTION_PENDING',
  CLOSED = 'CLOSED',

  // Common
  REJECTED = 'REJECTED',
}