export enum DocumentType {
  PAN = 'PAN',
  AADHAAR = 'AADHAAR',
  PHOTO = 'PHOTO',
  BANK_STATEMENT = 'BANK_STATEMENT',
  PROPERTY_DOCUMENT = 'PROPERTY_DOCUMENT',
  INCOME_PROOF = 'INCOME_PROOF',
  OTHER = 'OTHER'
}
