export enum ApplicationStage {
  LEAD = 'LEAD',
  FIELD_VERIFICATION = 'FIELD_VERIFICATION',
  BM_REVIEW = 'BM_REVIEW',
  CM_SCREENING = 'CM_SCREENING',
  CREDIT_MAKER = 'CREDIT_MAKER',
  CREDIT_CHECKER = 'CREDIT_CHECKER',
  LEGAL_VALUATION = 'LEGAL_VALUATION',
  SANCTION_KFS = 'SANCTION_KFS',
  DOCUMENTATION_PDD = 'DOCUMENTATION_PDD',
  OPS_MAKER = 'OPS_MAKER',
  OPS_CHECKER = 'OPS_CHECKER',
  DISBURSEMENT = 'DISBURSEMENT',
  ACTIVE_LOAN = 'ACTIVE_LOAN',
  COLLECTIONS = 'COLLECTIONS',
  CLOSURE = 'CLOSURE'
}
