import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsBoolean, IsDateString, IsEmail, IsEnum, IsInt, IsMobilePhone, IsNumber, IsOptional, IsString, Length, Max, Min } from 'class-validator';
import { BureauStatus, CustomerType, Gender, MaritalStatus, OccupationType } from '../../../common/enums/customer-profile.enum';

export class CreateCustomerProfileDto {
  @ApiProperty() @Type(() => Number) @IsInt() applicationId: number;
  @ApiProperty({ enum: CustomerType }) @IsEnum(CustomerType) customerType: CustomerType;
  @ApiProperty() @IsString() @Length(1, 80) firstName: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(1, 80) middleName?: string;
  @ApiProperty() @IsString() @Length(1, 80) lastName: string;
  @ApiProperty() @IsMobilePhone('en-IN') mobile: string;
  @ApiPropertyOptional() @IsOptional() @IsEmail() email?: string;
  @ApiPropertyOptional() @IsOptional() @IsDateString() dob?: string;
  @ApiPropertyOptional({ enum: Gender }) @IsOptional() @IsEnum(Gender) gender?: Gender;
  @ApiPropertyOptional({ enum: MaritalStatus }) @IsOptional() @IsEnum(MaritalStatus) maritalStatus?: MaritalStatus;
  @ApiPropertyOptional() @IsOptional() @IsString() education?: string;
  @ApiPropertyOptional({ enum: OccupationType }) @IsOptional() @IsEnum(OccupationType) occupationType?: OccupationType;
  @ApiPropertyOptional() @IsOptional() @IsString() businessName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() designation?: string;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() monthlyIncome?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() annualIncome?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(10, 10) panNumber?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() panVerified?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(12, 12) aadhaarNumber?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() aadhaarVerified?: boolean;
  @ApiPropertyOptional() @IsOptional() @IsString() ckycNumber?: string;
  @ApiPropertyOptional() @IsOptional() @IsBoolean() ckycVerified?: boolean;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(300) @Max(900) bureauScore?: number;
  @ApiPropertyOptional({ enum: BureauStatus }) @IsOptional() @IsEnum(BureauStatus) bureauStatus?: BureauStatus;
  @ApiPropertyOptional() @IsOptional() @IsString() currentAddress?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() currentCity?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() currentState?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(6, 6) currentPincode?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() permanentAddress?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() permanentCity?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() permanentState?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(6, 6) permanentPincode?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() propertyType?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() propertyAddress?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() propertyCity?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() propertyState?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(6, 6) propertyPincode?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() ownershipType?: string;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() marketValue?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() distressValue?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() bankName?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() accountNumber?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() @Length(11, 11) ifsc?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() branchName?: string;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() averageBalance?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() foir?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() eligibleAmount?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() roi?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() tenure?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() emi?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() recommendedAmount?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsNumber() recommendedRoi?: number;
  @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() recommendedTenure?: number;
  @ApiPropertyOptional() @IsOptional() @IsString() rmRecommendation?: string;
  @ApiPropertyOptional() @IsOptional() @IsString() remarks?: string;
}
