export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  NEW = 'NEW',

  IN_PROGRESS = 'IN_PROGRESS',

  SUBMITTED_TO_BM = 'SUBMITTED_TO_BM',

  BM_PENDING = 'BM_PENDING',
  BM_APPROVED = 'BM_APPROVED',

  CM_PENDING = 'CM_PENDING',
  CM_APPROVED = 'CM_APPROVED',

  CREDIT_PENDING = 'CREDIT_PENDING',
  CREDIT_APPROVED = 'CREDIT_APPROVED',

  LEGAL_PENDING = 'LEGAL_PENDING',
  LEGAL_APPROVED = 'LEGAL_APPROVED',

  VALUATION_PENDING = 'VALUATION_PENDING',
  VALUATION_APPROVED = 'VALUATION_APPROVED',

  SANCTION_PENDING = 'SANCTION_PENDING',
  SANCTION_APPROVED = 'SANCTION_APPROVED',

  AGREEMENT_PENDING = 'AGREEMENT_PENDING',
  AGREEMENT_COMPLETED = 'AGREEMENT_COMPLETED',

  DISBURSEMENT_PENDING = 'DISBURSEMENT_PENDING',
  DISBURSED = 'DISBURSED',

  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  CLOSED = 'CLOSED',
}