export const APPLICATION_STAGES = [
  'LEAD',
  'FIELD_VERIFICATION',
  'BM_REVIEW',
  'CM_SCREENING',
  'CREDIT_MAKER',
  'CREDIT_CHECKER',
  'LEGAL_VALUATION',
  'SANCTION_KFS',
  'DOCUMENTATION_PDD',
  'OPS_MAKER',
  'OPS_HEAD',
  'OPS_CHECKER',
  'DISBURSEMENT',
  'ACTIVE_LOAN',
  'COLLECTIONS',
  'CLOSURE'
];
