export const PERMISSIONS = {
  APPLICATION_READ: 'application:read',
  APPLICATION_CREATE: 'application:create',
  APPLICATION_UPDATE: 'application:update',
  APPLICATION_TRANSITION: 'application:transition',
  VISIT_CREATE: 'visit:create',
  DOCUMENT_UPLOAD: 'document:upload',
  DOCUMENT_READ: 'document:read',
  DOCUMENT_DELETE: 'document:delete',
  CUSTOMER_PROFILE_MANAGE: 'customer-profile:manage',
  CONTACT_PERSON_MANAGE: 'contact-person:manage',
  CO_APPLICANT_MANAGE: 'co-applicant:manage',
  NOTIFICATION_READ: 'notification:read',
  DASHBOARD_READ: 'dashboard:read',
  BM_APPROVE: 'bm:approve',
  CREDIT_APPROVE: 'credit:approve',
  PAYMENT_CHECK: 'payment:check',
  DISBURSEMENT_APPROVE: 'disbursement:approve',
  AUDIT_READ: 'audit:read'
} as const;
